apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack
  namespace: openshift-logging
spec:
  limits:
    global:
      retention:
        days: 3
  size: 1x.small
  storageClassName: nfs-csi
  storage:
    schemas:
    - effectiveDate: "2026-09-29"
      version: v13
    secret:
      name: lokistack-s3
      type: s3
    tls:
      caName: openshift-service-ca.crt
  tenants:
    mode: openshift-logging
